"""
Agent Skill: Update Dashboard
This skill allows Claude Code to update the dashboard with current status
"""
import json
from pathlib import Path
from datetime import datetime


def update_dashboard(status_updates: dict = None, activity: str = None) -> dict:
    """
    Update the dashboard with current status information

    Args:
        status_updates (dict): Dictionary of status updates to incorporate
        activity (str): Recent activity to add to the dashboard

    Returns:
        dict: Result of the dashboard update
    """
    project_root = Path(__file__).parent.parent  # Go up to project root
    dashboard_path = project_root / "dashboard.md"

    try:
        # Read the current dashboard content
        if dashboard_path.exists():
            current_content = dashboard_path.read_text(encoding='utf-8')
        else:
            # Create a basic dashboard if it doesn't exist
            current_content = """# AI Employee Dashboard

## Overview
Welcome to your AI Employee Dashboard. This system monitors your personal and business tasks, helping you stay organized and productive.

## Status Summary
- **Inbox**: 0 items
- **Needs Action**: 0 items
- **Pending Approval**: 0 items
- **Completed Today**: 0 items

## Recent Activity
- [No recent activity]

## Current Tasks
- [No active tasks]

## System Status
- Watchers: [Offline]
- MCP Servers: [Not running]
- Last Updated: {{DATE}}

---
*Generated by AI Employee Bronze Tier - {{DATETIME}}*
"""

        # Count items in each folder
        inbox_folder = project_root / "inbox"
        needs_action_folder = project_root / "needs_action"
        pending_approval_folder = project_root / "pending_approval"
        done_folder = project_root / "done"

        inbox_count = len(list(inbox_folder.glob("*"))) if inbox_folder.exists() else 0
        needs_action_count = len(list(needs_action_folder.glob("*"))) if needs_action_folder.exists() else 0
        pending_approval_count = len(list(pending_approval_folder.glob("*"))) if pending_approval_folder.exists() else 0
        done_count = len(list(done_folder.glob("*.md"))) if done_folder.exists() else 0

        # Get today's completed items
        today_str = datetime.now().strftime('%Y-%m-%d')
        today_done_count = 0
        if done_folder.exists():
            for file in done_folder.glob("*.md"):
                # Simple check if the file was modified today
                import time
                file_time = time.localtime(file.stat().st_mtime)
                file_date = time.strftime('%Y-%m-%d', file_time)
                if file_date == today_str:
                    today_done_count += 1

        # Update status summary
        status_summary_start = current_content.find("## Status Summary")
        status_summary_end = current_content.find("## Recent Activity")

        if status_summary_start != -1 and status_summary_end != -1:
            old_status = current_content[status_summary_start:status_summary_end]
            new_status = f"""## Status Summary
- **Inbox**: {inbox_count} items
- **Needs Action**: {needs_action_count} items
- **Pending Approval**: {pending_approval_count} items
- **Completed Today**: {today_done_count} items
- **Total Completed**: {done_count} items"""
            current_content = current_content.replace(old_status, new_status)

        # Add recent activity if provided
        if activity:
            activity_section_start = current_content.find("## Recent Activity")
            if activity_section_start != -1:
                next_section_start = current_content.find("## ", activity_section_start + 1)
                if next_section_start == -1:
                    next_section_start = len(current_content)

                activity_section = current_content[activity_section_start:next_section_start]
                new_activity = f"""## Recent Activity
- [{datetime.now().strftime('%H:%M %m/%d')}] {activity}

{activity_section[19:]}"""  # 19 = len("## Recent Activity\n")
                current_content = current_content.replace(activity_section, new_activity)

        # Update last updated timestamp
        current_content = current_content.replace("{{DATETIME}}", datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        current_content = current_content.replace("{{DATE}}", datetime.now().strftime('%Y-%m-%d'))

        # Write the updated content back to the dashboard
        dashboard_path.write_text(current_content, encoding='utf-8')

        return {
            "status": "success",
            "message": "Dashboard updated successfully",
            "dashboard_path": str(dashboard_path),
            "timestamp": datetime.now().isoformat(),
            "updates": {
                "inbox_count": inbox_count,
                "needs_action_count": needs_action_count,
                "pending_approval_count": pending_approval_count,
                "today_done_count": today_done_count,
                "total_done_count": done_count
            }
        }

    except Exception as e:
        return {
            "status": "error",
            "message": f"Error updating dashboard: {str(e)}",
            "timestamp": datetime.now().isoformat()
        }


def get_dashboard_status() -> dict:
    """
    Get the current status from the dashboard

    Returns:
        dict: Current dashboard status information
    """
    project_root = Path(__file__).parent.parent
    dashboard_path = project_root / "dashboard.md"

    if not dashboard_path.exists():
        return {
            "status": "error",
            "message": "Dashboard file does not exist",
            "timestamp": datetime.now().isoformat()
        }

    try:
        content = dashboard_path.read_text(encoding='utf-8')

        # Count items in each folder
        inbox_folder = project_root / "inbox"
        needs_action_folder = project_root / "needs_action"
        pending_approval_folder = project_root / "pending_approval"
        done_folder = project_root / "done"

        inbox_count = len(list(inbox_folder.glob("*"))) if inbox_folder.exists() else 0
        needs_action_count = len(list(needs_action_folder.glob("*"))) if needs_action_folder.exists() else 0
        pending_approval_count = len(list(pending_approval_folder.glob("*"))) if pending_approval_folder.exists() else 0
        done_count = len(list(done_folder.glob("*.md"))) if done_folder.exists() else 0

        return {
            "status": "success",
            "dashboard_path": str(dashboard_path),
            "content_preview": content[:500] + "..." if len(content) > 500 else content,
            "folder_counts": {
                "inbox": inbox_count,
                "needs_action": needs_action_count,
                "pending_approval": pending_approval_count,
                "done": done_count
            },
            "timestamp": datetime.now().isoformat()
        }

    except Exception as e:
        return {
            "status": "error",
            "message": f"Error reading dashboard: {str(e)}",
            "timestamp": datetime.now().isoformat()
        }


# Example usage function
def run_example():
    """Example of how to use the update_dashboard skill"""
    result = update_dashboard(
        activity="System initialized and monitoring active",
        status_updates={"watchers": "active", "last_check": datetime.now().isoformat()}
    )
    print("Dashboard update result:", json.dumps(result, indent=2))

    status_result = get_dashboard_status()
    print("Dashboard status:", json.dumps(status_result, indent=2))


if __name__ == "__main__":
    run_example()